import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { Link, NavLink, useNavigate, useParams } from "react-router-dom";
import { ApiError, authToken, get, post, put, setAuthToken } from "../api/client";
import { AppRouter } from "./router";
import type { Artifact, AuditEvent, InboxItem, LoginResponse, ModelConnection, Page, Project, RepositoryBinding, RepositoryChange, Run, Task, User, ValidationReport, WorkflowEdge, WorkflowNode, WorkflowVersion } from "../api/contracts";
import { openEventStream } from "../api/events";
import { createModelConnection, deleteModelConnection, getModelUsage, testModelConnection } from "../features/model-connections";
import { createProject, deleteProject } from "../features/projects";
import { decideInbox } from "../features/inbox";
import { cancelRun, pauseRun, resumeRun, retryTask } from "../features/run-monitor";
import { saveWorkflowGraph, validateWorkflow, publishWorkflow } from "../features/workflow-designer";
import { mergeRepositoryChange } from "../features/repository-review";
import { listSkills } from "../features/skills";
import { listTools, simulatePolicy } from "../features/tools";
import { listRoles, publishRole } from "../features/roles";
import { getProjectorStatus, listNodes } from "../features/settings";

export function App() { return authToken() ? <Shell><AppRouter /></Shell> : <LoginPage />; }

export function LoginPage() {
  const navigate = useNavigate();
  const [username, setUsername] = useState(""); const [password, setPassword] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { const result = await post<LoginResponse>("/api/v1/auth/login", { username, password }); const token = result.access_token ?? result.token; if (!token) throw new Error("登录响应缺少 token"); setAuthToken(token); navigate("/dashboard"); window.location.reload(); }
    catch (e) { setError(formatError(e, "登录失败")); } finally { setBusy(false); }
  }
  return <main className="login"><form onSubmit={submit} className="login-card"><div className="eyebrow">CONTROL PLANE</div><h1>Multi-Agent Flow</h1><p>统一管理项目、工作流与运行任务</p><label>用户名<input value={username} onChange={e => setUsername(e.target.value)} required autoComplete="username" /></label><label>密码<input type="password" value={password} onChange={e => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <div className="error">{error}</div>}<button disabled={busy}>{busy ? "登录中…" : "登录"}</button></form></main>;
}

function Shell({ children }: { children: ReactNode }) {
  const navigate = useNavigate(); const [user, setUser] = useState<User | null>(null);
  useEffect(() => { let alive = true; void get<User>("/api/v1/me").then(v => alive && setUser(v)).catch(() => { setAuthToken(null); navigate("/login"); }); return () => { alive = false; }; }, [navigate]);
  async function logout() { try { await post<void>("/api/v1/auth/logout"); } catch { /* logout is local even when server is unavailable */ } finally { setAuthToken(null); navigate("/login"); window.location.reload(); } }
  const can = (permission: string) => !user?.permissions?.length || user.permissions.includes("ADMIN") || user.permissions.includes(permission);
  const links = [["/dashboard", "Dashboard", "read:dashboard"], ["/projects", "项目", "read:projects"], ["/models", "模型", "read:model_connections"], ["/workflows", "工作流", "read:workflows"], ["/capabilities", "能力", "read:capabilities"], ["/inbox", "Inbox", "read:inbox"], ["/settings", "设置", "read:settings"]].filter(([, , permission]) => can(permission));
  return <div className="shell"><aside><Link className="brand" to="/dashboard"><span>MAF</span><small>Multi-Agent Flow</small></Link><nav>{links.map(([to, label]) => <NavLink key={to} to={to}>{label}</NavLink>)}</nav><button className="logout" onClick={logout}>退出登录</button></aside><section className="content"><header><span className="connection-dot" />{user?.display_name ?? user?.username ?? ""}{user?.roles?.length ? <small>{user.roles.join(" · ")}</small> : null}</header><div className="page">{children}</div></section></div>;
}

export function canPerform(user: User | null, permission: string) {
  return Boolean(user && (!user.permissions?.length || user.permissions.includes("ADMIN") || user.permissions.includes(permission)));
}

export function formatError(error: unknown, fallback = "请求失败") { if (error instanceof ApiError) return `${error.message}${error.traceId ? `（Trace ID: ${error.traceId}）` : ""}`; return error instanceof Error ? error.message : fallback; }
export function asList<T>(value: Page<T> | T[] | null | undefined): T[] { return Array.isArray(value) ? value : value?.items ?? []; }
function useResource<T>(path: string) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [revision, setRevision] = useState(0);
  const reload = useCallback(() => setRevision(v => v + 1), []);
  useEffect(() => { let alive = true; setLoading(true); setError(""); void get<T>(path).then(v => alive && setData(v)).catch(e => alive && setError(formatError(e))).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [path, revision]);
  return { data, error, loading, reload };
}
function PageTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <div className="page-title"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }
function State({ children, tone = "muted" }: { children: ReactNode; tone?: "muted" | "error" | "success" }) { return <div className={`state ${tone}`}>{children}</div>; }
function ErrorNotice({ error }: { error: string }) { return error ? <div className="error notice">{error}</div> : null; }
function Status({ value }: { value?: string }) { const text = value ?? "UNKNOWN"; return <span className={`status status-${text.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>{text}</span>; }

export function DashboardPage() {
  const projects = useResource<Page<Project> | Project[]>("/api/v1/projects"); const inbox = useResource<InboxItem[]>("/api/v1/inbox?status=PENDING"); const projectList = asList(projects.data);
  return <><PageTitle title="Dashboard" subtitle="项目、运行与审批的实时摘要" action={<Link className="button" to="/projects">管理项目</Link>} /><div className="stats"><div><b>{projectList.length}</b><span>项目</span></div><div><b>{inbox.data?.length ?? 0}</b><span>待处理审批</span></div><div><b>{projectList.filter(p => p.status === "ACTIVE" || p.status === "RUNNING").length}</b><span>活跃项目</span></div></div><section className="panel"><div className="panel-heading"><h3>项目概览</h3><button className="secondary" onClick={projects.reload}>刷新</button></div>{projects.error ? <State tone="error">{projects.error}</State> : projects.loading ? <State>加载中…</State> : <table><thead><tr><th>名称</th><th>状态</th><th>仓库</th><th>更新时间</th></tr></thead><tbody>{projectList.map(p => <tr key={p.id}><td><Link to={`/projects/${p.id}`}>{p.name}</Link></td><td><Status value={p.status} /></td><td>{p.repository_count ?? 0}</td><td>{formatDate(p.updated_at)}</td></tr>)}{!projectList.length && <tr><td colSpan={4}><State>暂无项目，先创建一个项目吧</State></td></tr>}</tbody></table>}</section><section className="panel quick-links"><h3>快速入口</h3><Link to="/inbox">查看待办审批 →</Link><Link to="/workflows">编辑工作流 →</Link><Link to="/models">验证模型连接 →</Link></section></>;
}

export function ProjectsPage() {
  const projects = useResource<Page<Project> | Project[]>("/api/v1/projects"); const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", description: "" }); const list = asList(projects.data);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await createProject(form); setForm({ name: "", description: "" }); setShowCreate(false); projects.reload(); } catch (e) { setError(formatError(e)); } }
  async function remove(project: Project) { if (!window.confirm(`确认删除项目“${project.name}”？`)) return; try { await deleteProject(project.id); projects.reload(); } catch (e) { setError(formatError(e)); } }
  return <><PageTitle title="项目" subtitle="项目输入、仓库绑定与默认工作流" action={<button onClick={() => setShowCreate(v => !v)}>{showCreate ? "取消" : "新建项目"}</button>} />{error && <ErrorNotice error={error} />}{showCreate && <form className="panel form-grid" onSubmit={submit}><label>项目名称<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>描述<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><button>创建项目</button></form>}{projects.error ? <State tone="error">{projects.error}</State> : projects.loading ? <State>加载中…</State> : <div className="grid">{list.map(p => <article className="card" key={p.id}><div className="card-heading"><h3><Link to={`/projects/${p.id}`}>{p.name}</Link></h3><Status value={p.status} /></div><p>{p.description || "暂无描述"}</p><small>{p.repository_count ?? 0} 个仓库 · 版本 {p.version ?? "-"}</small><div className="card-actions"><Link className="secondary" to={`/projects/${p.id}`}>查看详情</Link><button className="danger ghost" onClick={() => void remove(p)}>删除</button></div></article>)}{!list.length && <State>暂无项目</State>}</div>}</>;
}

export function ProjectDetailPage() {
  const { projectId = "" } = useParams(); const project = useResource<Project>(`/api/v1/projects/${projectId}`); const repos = useResource<Page<RepositoryBinding> | RepositoryBinding[]>(`/api/v1/projects/${projectId}/repositories`); const [notice, setNotice] = useState(""); const [repo, setRepo] = useState({ repository_url: "", branch: "main", credential_type: "NONE" });
  async function bindRepository(event: FormEvent) { event.preventDefault(); try { await post(`/api/v1/projects/${projectId}/repositories`, repo); setRepo({ repository_url: "", branch: "main", credential_type: "NONE" }); setNotice("仓库已绑定，等待验证"); repos.reload(); } catch (e) { setNotice(formatError(e)); } }
  async function verify(id: string) { try { await post(`/api/v1/repositories/${id}/verify`); repos.reload(); } catch (e) { setNotice(formatError(e)); } }
  if (project.loading) return <State>加载中…</State>; if (project.error || !project.data) return <State tone="error">{project.error || "项目不存在"}</State>;
  return <><PageTitle title={project.data.name} subtitle={project.data.description} action={<Link className="secondary" to="/projects">返回项目列表</Link>} />{notice && <div className="notice">{notice}</div>}<section className="panel"><div className="panel-heading"><h3>项目状态</h3><Status value={project.data.status} /></div><dl className="details"><dt>项目 ID</dt><dd>{project.data.id}</dd><dt>默认工作流版本</dt><dd>{project.data.default_workflow_version_id || "未配置"}</dd><dt>数据版本</dt><dd>{project.data.version ?? "-"}</dd></dl></section><section className="panel"><h3>仓库绑定</h3><form className="inline-form" onSubmit={bindRepository}><input placeholder="https://github.com/org/repo.git" required value={repo.repository_url} onChange={e => setRepo({ ...repo, repository_url: e.target.value })} /><input placeholder="分支" value={repo.branch} onChange={e => setRepo({ ...repo, branch: e.target.value })} /><button>绑定</button></form>{repos.loading ? <State>读取仓库…</State> : <table><thead><tr><th>仓库</th><th>分支</th><th>凭据</th><th>验证</th><th /></tr></thead><tbody>{asList(repos.data).map(r => <tr key={r.id}><td>{r.repository_url}</td><td>{r.branch}</td><td>{r.credential_configured ? "已配置" : "未配置"}</td><td><Status value={r.verified ? "VERIFIED" : "PENDING"} /></td><td>{!r.verified && <button className="secondary" onClick={() => void verify(r.id)}>验证</button>}</td></tr>)}</tbody></table>}</section></>;
}

export function ModelPage() {
  const models = useResource<ModelConnection[] | Page<ModelConnection>>("/api/v1/model-connections"); const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [usageFilter, setUsageFilter] = useState(""); const [usage, setUsage] = useState<Array<Record<string, unknown>>>([]); const [form, setForm] = useState({ name: "", provider: "", model_id: "", api_base: "", credential_type: "API_KEY", credential_value: "" });
  useEffect(() => { void getModelUsage(usageFilter ? `project_id=${encodeURIComponent(usageFilter)}` : "").then(v => setUsage(asList(v as never))).catch(() => setUsage([])); }, [usageFilter]);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await createModelConnection(form); setForm({ name: "", provider: "", model_id: "", api_base: "", credential_type: "API_KEY", credential_value: "" }); setShowCreate(false); models.reload(); } catch (e) { setError(formatError(e)); } }
  async function test(id: string) { setBusy(id); try { await testModelConnection(id); models.reload(); } catch (e) { setError(formatError(e)); } finally { setBusy(""); } }
  async function remove(model: ModelConnection) { if (!window.confirm(`确认删除“${model.name}”？`)) return; try { await deleteModelConnection(model.id); models.reload(); } catch (e) { setError(formatError(e)); } }
  const list = asList(models.data);
  return <><PageTitle title="模型连接" subtitle="凭据只在创建或轮换时输入，列表永不回显密钥" action={<button onClick={() => setShowCreate(v => !v)}>{showCreate ? "取消" : "新增连接"}</button>} />{error && <ErrorNotice error={error} />}{showCreate && <form className="panel form-grid" onSubmit={submit}><div className="form-grid two"><label>名称<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>供应商<input required placeholder="openai / anthropic" value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })} /></label><label>模型 ID<input required value={form.model_id} onChange={e => setForm({ ...form, model_id: e.target.value })} /></label><label>API Base<input type="url" value={form.api_base} onChange={e => setForm({ ...form, api_base: e.target.value })} /></label></div><label>API Key（只写入，不会回显）<input type="password" required value={form.credential_value} onChange={e => setForm({ ...form, credential_value: e.target.value })} /></label><button>保存连接</button></form>}<section className="panel">{models.error ? <State tone="error">{models.error}</State> : models.loading ? <State>加载中…</State> : <table><thead><tr><th>名称</th><th>供应商 / 模型</th><th>能力矩阵</th><th>状态</th><th /></tr></thead><tbody>{list.map(m => <tr key={m.id}><td>{m.name}</td><td>{m.provider ?? "-"} / {m.model_id ?? "-"}</td><td>{m.capabilities ? Object.entries(m.capabilities).filter(([, value]) => value).map(([key]) => key).join(", ") : m.model_count ?? "-"}</td><td><Status value={m.status ?? "UNVERIFIED"} /></td><td className="actions"><button className="secondary" disabled={busy === m.id} onClick={() => void test(m.id)}>{busy === m.id ? "验证中…" : "测试"}</button><button className="danger ghost" onClick={() => void remove(m)}>删除</button></td></tr>)}{!list.length && <tr><td colSpan={5}><State>暂无模型连接</State></td></tr>}</tbody></table>}</section><section className="panel"><div className="panel-heading"><h3>用量</h3><input aria-label="按项目过滤" placeholder="项目 ID（可选）" value={usageFilter} onChange={e => setUsageFilter(e.target.value)} /></div><table><thead><tr><th>项目</th><th>Run</th><th>模型</th><th>Tokens</th><th>成本</th></tr></thead><tbody>{usage.map((item, i) => <tr key={i}><td>{String(item.project_id ?? "-")}</td><td>{String(item.run_id ?? "-")}</td><td>{String(item.model ?? item.model_id ?? "-")}</td><td>{String(item.tokens ?? "-")}</td><td>{String(item.cost ?? "-")}</td></tr>)}</tbody></table></section></>;
}

const defaultNodes: WorkflowNode[] = [{ id: "start", type: "START", label: "开始", x: 40, y: 80 }, { id: "task", type: "AGENT", label: "执行节点", x: 260, y: 80 }, { id: "end", type: "END", label: "结束", x: 480, y: 80 }];
const defaultEdges: WorkflowEdge[] = [{ id: "start-task", source: "start", target: "task" }, { id: "task-end", source: "task", target: "end" }];
export function WorkflowPage() {
  const { workflowId = "", versionId = "" } = useParams(); const [nodes, setNodes] = useState(defaultNodes); const [edges, setEdges] = useState(defaultEdges); const [version, setVersion] = useState<WorkflowVersion | null>(versionId ? null : { id: "local", status: "DRAFT", nodes: defaultNodes, edges: defaultEdges }); const [validation, setValidation] = useState<ValidationReport | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function createDraft(event: FormEvent) { event.preventDefault(); const name = new FormData(event.currentTarget as HTMLFormElement).get("name"); setBusy("create"); try { const workflow = await post<{ id: string }>("/api/v1/workflows", { name, key: String(name).toLowerCase().replace(/\s+/g, "-"), description: "", idempotency_key: crypto.randomUUID() }); const draft = await post<WorkflowVersion>(`/api/v1/workflows/${workflow.id}/versions`, { based_on_version_id: null, change_summary: "Initial draft", idempotency_key: crypto.randomUUID() }); window.location.href = `/workflows/${workflow.id}/versions/${draft.id}`; } catch (e) { setMessage(formatError(e)); } finally { setBusy(""); } }
  async function save() { if (!versionId) { setMessage("请先创建工作流草稿"); return; } setBusy("save"); try { const saved = await saveWorkflowGraph(versionId, { graph: { start_node_key: nodes[0]?.id ?? "", nodes, edges } }, version?.expected_version ?? version?.version_no ?? 1); setVersion(saved as WorkflowVersion); setMessage("草稿已保存"); } catch (e) { setMessage(formatError(e)); } finally { setBusy(""); } }
  async function validate() { if (!versionId) return; setBusy("validate"); try { const report = await validateWorkflow(versionId) as ValidationReport; setValidation(report); setMessage(report.valid === false || report.errors?.length ? `校验失败：${report.errors?.map(e => e.message).join("；")}` : "静态校验通过"); } catch (e) { setMessage(formatError(e)); } finally { setBusy(""); } }
  async function publish() { if (!versionId) return; setBusy("publish"); try { const result = await publishWorkflow(versionId, version?.expected_version ?? version?.version_no ?? 1); setVersion(result as WorkflowVersion); setMessage("已发布"); } catch (e) { setMessage(formatError(e)); } finally { setBusy(""); } }
  if (!versionId) return <><PageTitle title="Workflow 设计器" subtitle="确定性 DAG、静态校验与版本发布" /><form className="panel compact-form" onSubmit={createDraft}><h3>创建工作流</h3><input name="name" required placeholder="例如：代码交付流水线" /><button disabled={busy === "create"}>{busy === "create" ? "创建中…" : "创建草稿"}</button>{message && <ErrorNotice error={message} />}</form><section className="panel workflow-preview"><h3>编辑器预览</h3><GraphCanvas nodes={defaultNodes} edges={defaultEdges} /></section></>;
  const readOnly = version?.status === "PUBLISHED";
  return <><PageTitle title="Workflow 设计器" subtitle={`版本 ${version?.version_no ?? "-"} · ${version?.status ?? "DRAFT"}`} action={<Link className="secondary" to="/workflows">返回工作流</Link>} />{message && <div className="notice">{message}</div>}<section className="panel workflow-editor"><GraphCanvas nodes={nodes} edges={edges} /><div className="node-list">{nodes.map((node, index) => <label key={node.id}>节点 {index + 1}<input disabled={readOnly} value={node.label ?? ""} onChange={e => setNodes(v => v.map(n => n.id === node.id ? { ...n, label: e.target.value } : n))} /></label>)}</div><div className="toolbar"><button disabled={readOnly || busy === "save"} onClick={() => void save()}>保存草稿</button><button className="secondary" disabled={busy === "validate"} onClick={() => void validate()}>静态校验</button><button className="secondary" disabled={readOnly || busy === "publish"} onClick={() => void publish()}>发布版本</button></div></section>{validation && <section className="panel"><h3>发布前依赖摘要</h3><p>可达节点：{validation.reachable_node_keys?.join(", ") || "-"}</p>{validation.errors?.length ? <ul className="check-list">{validation.errors.map((error, index) => <li key={index}><Status value="ERROR" /> <button className="link-button" onClick={() => document.getElementById(error.node_id ?? error.edge_id ?? "")?.scrollIntoView({ behavior: "smooth" })}>{error.code ?? "校验"}</button>：{error.message}</li>)}</ul> : <p>Role、Contract、返工依赖校验通过。</p>}</section>}</>;
}
function GraphCanvas({ nodes, edges }: { nodes: WorkflowNode[]; edges: WorkflowEdge[] }) { return <div className="graph-canvas">{nodes.map((n, i) => <span className={`graph-node node-${n.type.toLowerCase()}`} key={n.id} style={{ left: `${n.x ?? i * 220 + 40}px`, top: `${n.y ?? 70}px` }}>{n.label ?? n.type}</span>)}<div className="graph-edges">{edges.map(e => <span key={e.id ?? `${e.source}-${e.target}`}>→</span>)}</div></div>; }

export function RunPage() {
  const { runId = "" } = useParams(); const run = useResource<Run>(`/api/v1/runs/${runId}`); const tasks = useResource<Page<Task> | Task[]>(`/api/v1/runs/${runId}/tasks`); const graph = useResource<{ nodes?: WorkflowNode[]; edges?: WorkflowEdge[] }>(`/api/v1/runs/${runId}/graph`); const [events, setEvents] = useState<string[]>([]); const [command, setCommand] = useState(""); const [commandBusy, setCommandBusy] = useState("");
  useEffect(() => openEventStream(`/api/v1/runs/${runId}/events`, { onEvent: event => setEvents(v => [...v.slice(-49), `${event.id ?? "-"} ${event.event}: ${JSON.stringify(event.data)}`] ), onError: e => setCommand(e.message) }), [runId]);
  async function control(action: "pause" | "resume" | "cancel") { setCommandBusy(action); try { const fn = action === "pause" ? pauseRun : action === "resume" ? resumeRun : cancelRun; await fn(runId, run.data?.version); setCommand(`${action.toUpperCase()} 命令已受理，状态将异步收敛`); run.reload(); } catch (e) { setCommand(formatError(e)); } finally { setCommandBusy(""); } }
  const list = asList(tasks.data); const completed = list.filter(t => ["DONE", "ACCEPTED", "COMPLETED"].includes(t.status)).length; const progress = run.data?.progress ?? (list.length ? Math.round(completed / list.length * 100) : 0);
  return <><PageTitle title={`Run ${runId}`} subtitle="实时状态、任务进度与控制命令" action={<Link className="secondary" to={run.data?.project_id ? `/projects/${run.data.project_id}` : "/dashboard"}>返回项目</Link>} />{command && <div className="notice">{command}</div>}<section className="panel run-summary"><div><span className="eyebrow">STATUS</span><h3><Status value={run.data?.status} /></h3><p>Control commit：<code>{run.data?.control_commit ?? "-"}</code></p><p>分支：{run.data?.branch ?? "-"}</p></div><div className="progress-wrap"><b>{progress}%</b><div className="progress"><span style={{ width: `${progress}%` }} /></div><small>{completed}/{list.length || run.data?.total_tasks || 0} 个任务完成</small></div><div className="command-buttons"><button disabled={commandBusy !== ""} onClick={() => void control("pause")}>暂停</button><button className="secondary" disabled={commandBusy !== ""} onClick={() => void control("resume")}>恢复</button><button className="danger" disabled={commandBusy !== ""} onClick={() => void control("cancel")}>取消运行</button></div></section>{run.error && <State tone="error">{run.error}</State>}<section className="panel"><div className="panel-heading"><h3>任务</h3><button className="secondary" onClick={tasks.reload}>刷新</button></div>{tasks.loading ? <State>加载中…</State> : <div className="task-table">{list.map(t => <div className="row" key={t.id}><span><b>{t.name ?? t.id}</b><small>{t.owner ?? "未分配"} · epoch {t.epoch ?? "-"}</small></span><Status value={t.status} /><span>{t.progress ?? 0}%</span><button className="ghost" onClick={() => void retryTask(t.id)}>重试</button></div>)}{!list.length && <State>暂无任务</State>}</div>}</section><section className="panel"><h3>运行图</h3>{graph.loading ? <State>读取图状态…</State> : <GraphCanvas nodes={graph.data?.nodes ?? []} edges={graph.data?.edges ?? []} />}</section><section className="panel"><h3>事件时间线 <small className="live">LIVE</small></h3><pre className="event-log">{events.join("\n") || "等待事件…"}</pre></section></>;
}

export function InboxPage() {
  const inbox = useResource<InboxItem[]>("/api/v1/inbox"); const [selected, setSelected] = useState<InboxItem | null>(null); const [comment, setComment] = useState(""); const [filter, setFilter] = useState("PENDING"); const [message, setMessage] = useState("");
  const list = inbox.data?.filter(i => filter === "ALL" || i.status === filter) ?? [];
  async function decide(decision: "APPROVE" | "REJECT" | "REQUEST_CHANGES") { if (!selected) return; try { await decideInbox(selected.id, decision, comment, selected.subject_version); setMessage("决定已提交"); setSelected(null); setComment(""); inbox.reload(); } catch (e) { setMessage(formatError(e)); } }
  return <><PageTitle title="Inbox" subtitle="审批、质量门禁与人工接管" action={<select value={filter} onChange={e => setFilter(e.target.value)}><option value="PENDING">待处理</option><option value="ALL">全部</option><option value="APPROVED">已批准</option><option value="REJECTED">已拒绝</option></select>} />{message && <div className="notice">{message}</div>}<section className="panel">{inbox.error ? <State tone="error">{inbox.error}</State> : inbox.loading ? <State>加载中…</State> : list.length ? <div className="inbox-list">{list.map(item => <button className={`inbox-item ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelected(item)}><span><b>{item.title ?? item.type ?? "待处理事项"}</b><small>{item.project_id ?? ""} · {formatDate(item.created_at)}</small></span><Status value={item.status} /></button>)}</div> : <State>暂无待办</State>}</section>{selected && <section className="panel decision"><div className="panel-heading"><h3>{selected.title ?? selected.type ?? "待处理事项"}</h3><button className="ghost" onClick={() => setSelected(null)}>关闭</button></div><p>{selected.description || "请检查关联的 artifact、评审和质量门禁后再决定。"}</p><small>subject version: {selected.subject_version ?? "-"}</small><textarea placeholder="决策说明（可选）" value={comment} onChange={e => setComment(e.target.value)} /><div className="actions"><button onClick={() => void decide("APPROVE")}>批准</button><button className="secondary" onClick={() => void decide("REQUEST_CHANGES")}>要求修改</button><button className="danger" onClick={() => void decide("REJECT")}>拒绝</button></div></section>}</>;
}

export function ReviewPage() {
  const { runId = "" } = useParams(); const change = useResource<RepositoryChange>(`/api/v1/runs/${runId}/repository-change`); const artifacts = useResource<Artifact[]>(`/api/v1/runs/${runId}/artifacts`); const [message, setMessage] = useState("");
  async function merge() { if (!change.data?.id || !change.data.head_commit) return; try { await mergeRepositoryChange(change.data.id, change.data.head_commit); setMessage("合并命令已提交"); change.reload(); } catch (e) { setMessage(formatError(e)); } }
  return <><PageTitle title="仓库终审" subtitle={`Run ${runId} 的变更、检查与工件`} />{message && <div className="notice">{message}</div>}<section className="panel"><div className="panel-heading"><h3>Repository change</h3><Status value={change.data?.final_gate} /></div>{change.loading ? <State>加载中…</State> : change.error ? <State tone="error">{change.error}</State> : <><dl className="details"><dt>Base</dt><dd><code>{change.data?.base_commit ?? "-"}</code></dd><dt>Head</dt><dd><code>{change.data?.head_commit ?? "-"}</code></dd><dt>分支</dt><dd>{change.data?.branch ?? "-"}</dd></dl><ul className="check-list">{change.data?.checks?.map(check => <li key={check.name}><Status value={check.status} /> {check.name}</li>)}</ul><button disabled={!change.data?.mergeable || change.data.final_gate !== "PASS" || !change.data.head_commit} onClick={() => void merge()}>合并变更</button></>}</section><section className="panel"><h3>Artifacts</h3>{artifacts.loading ? <State>加载中…</State> : <table><thead><tr><th>名称</th><th>类型</th><th>大小</th><th>校验和</th><th>内容</th></tr></thead><tbody>{(artifacts.data ?? []).map(a => <tr key={a.id}><td>{a.name ?? a.id}</td><td>{a.artifact_type ?? "-"}</td><td>{a.size_bytes ? `${Math.round(a.size_bytes / 1024)} KB` : "-"}</td><td><code>{a.checksum ?? "-"}</code></td><td>{(a.size_bytes ?? 0) > 512 * 1024 ? <a href={a.content_url} target="_blank" rel="noreferrer">下载大文件</a> : <code>{a.preview ?? "暂无预览"}</code>}</td></tr>)}</tbody></table>}</section></>;
}

export function SettingsPage() {
  const [settings, setSettings] = useState<Record<string, unknown>>({}); const [audit, setAudit] = useState<AuditEvent[]>([]); const [nodes, setNodes] = useState<Array<Record<string, unknown>>>([]); const [projector, setProjector] = useState<Record<string, unknown>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void Promise.all([get<Record<string, unknown>>("/api/v1/settings"), get<AuditEvent[]>("/api/v1/audit?limit=20"), listNodes(), getProjectorStatus()]).then(([s, a, n, p]) => { setSettings(s); setAudit(a); setNodes(n); setProjector(p); }).catch(e => setMessage(formatError(e))); }, []);
  async function save() { setBusy(true); try { await Promise.all(Object.entries(settings).map(([key, value]) => put(`/api/v1/settings/${encodeURIComponent(key)}`, { value }))); setMessage("设置已保存"); } catch (e) { setMessage(formatError(e)); } finally { setBusy(false); } }
  return <><PageTitle title="设置与审计" subtitle="系统能力、节点健康和关键操作记录" action={<button disabled={busy} onClick={() => void save()}>保存设置</button>} />{message && <div className="notice">{message}</div>}<section className="panel"><h3>系统设置</h3>{Object.keys(settings).length ? <div className="settings-grid">{Object.entries(settings).map(([key, value]) => <label key={key}>{key}<input value={typeof value === "string" ? value : JSON.stringify(value)} onChange={e => setSettings(v => ({ ...v, [key]: e.target.value }))} /></label>)}</div> : <State>暂无可编辑设置；Secret 仅展示配置状态，不会回显密钥。</State>}</section><section className="panel"><h3>节点与投影</h3><p>Git projector：<Status value={String(projector.status ?? "UNKNOWN")} /> commit <code>{String(projector.projected_control_commit ?? "-")}</code></p><table><thead><tr><th>节点</th><th>状态</th><th>能力</th><th>最后事件</th><th>错误</th></tr></thead><tbody>{nodes.map(node => <tr key={String(node.id ?? node.node_id)}><td>{String(node.name ?? node.id ?? "-")}</td><td><Status value={String(node.status ?? "UNKNOWN")} /></td><td>{Array.isArray(node.capabilities) ? node.capabilities.join(", ") : "-"}</td><td>{String(node.last_event_at ?? "-")}</td><td>{String(node.last_error ?? "-")}</td></tr>)}</tbody></table></section><section className="panel"><h3>审计记录</h3>{audit.length ? <table><thead><tr><th>时间</th><th>事件</th><th>资源</th><th>摘要</th></tr></thead><tbody>{audit.map(event => <tr key={event.id}><td>{formatDate(event.created_at)}</td><td>{event.event_type}</td><td>{event.resource_type ?? "-"} / {event.resource_id ?? "-"}</td><td>{event.summary ?? "-"}</td></tr>)}</tbody></table> : <State>暂无审计记录或当前用户不可见</State>}</section></>;
}

export function CapabilitiesPage() {
  const [skills, setSkills] = useState<unknown[]>([]); const [tools, setTools] = useState<unknown[]>([]); const [roles, setRoles] = useState<unknown[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([listSkills(), listTools(), listRoles()]).then(([s, t, r]) => { setSkills(asList(s as never)); setTools(asList(t as never)); setRoles(asList(r as never)); }).catch(e => setMessage(formatError(e))); }, []);
  async function simulate() { try { await simulatePolicy({ subject: "current-user", action: "execute", resource: "tool" }); setMessage("策略模拟完成"); } catch (e) { setMessage(formatError(e)); } }
  return <><PageTitle title="能力配置" subtitle="Skill、Tool、MCP 和 Role 版本管理" action={<button onClick={() => void simulate()}>模拟策略</button>} />{message && <div className="notice">{message}</div>}<div className="grid"><section className="panel"><h3>Skills ({skills.length})</h3>{skills.map((item, i) => <div className="row" key={i}>{String((item as Record<string, unknown>).name ?? (item as Record<string, unknown>).id ?? item)}</div>)}</section><section className="panel"><h3>Tools / MCP ({tools.length})</h3>{tools.map((item, i) => <div className="row" key={i}>{String((item as Record<string, unknown>).name ?? (item as Record<string, unknown>).key ?? item)}</div>)}</section><section className="panel"><h3>Roles ({roles.length})</h3>{roles.map((item, i) => { const role = item as Record<string, unknown>; const readonly = role.status === "PUBLISHED"; return <div className="row" key={i}><span>{String(role.name ?? role.id ?? item)} <Status value={String(role.status ?? "DRAFT")} /></span>{!readonly && Boolean(role.id) && <button className="secondary" onClick={() => void publishRole(String(role.id)).catch(e => setMessage(formatError(e)))}>发布</button>}</div>; })}</section></div></>;
}

function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString() : "-"; }
